### ISSUE TITLE
authorizationResolution not approving authenticated users

### ISSUE THREAD

**Issue by sidiboshut** [trikoder/oauth2-bundle#32] opened 2019-03-11 17:28 UTC
I am using a fork from this repo [ajgarlag]https://github.com/ajgarlag/oauth2-bundle/tree/feature/authorization_code).
I managed to set it up, but there is a bug regarding `AuthorizationRequestResolveEvent` which is not approving authenticated user, so there is unauthorised error being thrown after a user has successfully logged.

**Comment by alenpokos** [comment] 2019-03-12 08:10
@sidiboshut We are working with ajgarlag to incorporate these changes into main repo. As this is still work in progress it might not be safe to use it for other than development and testing.
Do you have any additional pointers to how you got the bug  / how to reproducte it or where it might be caused from?

**Comment by ajgarlag** [comment] 2019-03-12 08:55
@sidiboshut It would be useful to see the code of the listener that listen to the `AuthorizationRequestResolveEvent` to approve the authorization request.

**Comment by sidiboshut** [comment] 2019-03-12 09:09
@alenpokos I am using this in dev mode for now and using a fork from @ajgarlag fork.
To reproduce it, just do the normal setup and protect `/authrize` endpoint so only logged in users can access it.
You also need to set an authentication login form guard in you `security.yml` file.
This is where it's occurring and how I fixed it as a work around for now in my [fork](https://github.com/sidiboshut/oauth2-bundle/blob/feature/authorization_code/Event/AuthorizationRequestResolveEvent.php#L37).
Please let me know if you need more details.

**Comment by ajgarlag** [comment] 2019-03-12 09:15
Instead of [this change](https://github.com/sidiboshut/oauth2-bundle/commit/e777038fa1bdab6fb6e8d5435de919c57d21de47) to the event class, you should add an event listener to approve the authorization request.

See https://github.com/ajgarlag/oauth2-bundle/blob/feature%2Fauthorization_code/Tests/Acceptance/AuthorizationEndpointTest.php#L18

**Comment by sidiboshut** [comment] 2019-03-12 09:56
Yes I was just looking at that bit, it sounds a better fix.
I will do that instead.
Thx

**Comment by sidiboshut** [comment] 2019-03-12 10:29
I have added a Listener for it in [here](https://github.com/sidiboshut/oauth2-bundle/blob/feature/authorization_code/Controller/AuthorizationController.php#L49).

**Comment by X-Coder264** [comment] 2019-06-06 20:58
@sidiboshut We have merged #18 into the bundle. Does everything work for you with our `dev-master` version?

**Comment by X-Coder264** [comment] 2019-07-27 08:50
Closing due to inactivity. If you still have problems with this even with our `dev-master` version feel free to ping me and I'll reopen it again.

**Closed by X-Coder264** 2019-07-27 08:50 UTC
